### ISSUE TITLE
top-level lines inside a `Module` shouldn't be indented

### ISSUE THREAD

**Issue by rai-nhdaly** [ZacLN/DocumentFormat.jl#30]
Per Julia Docs:

> Note that the style is not to indent the body of the module, since that would typically lead to whole files being indented.

\- https://docs.julialang.org/en/v1.0.3/manual/modules/#Modules-and-files-1

------

However:
```julia
julia> println(DocumentFormat.format("""module M
       using DocumentFormat
       x = 5
       end"""))
module M
    using DocumentFormat
    x = 5
end
```

**Comment by rai-nhdaly** [comment]
Oops, sorry, i didn't realize this is already fixed on master! :) Closing this issue!

**Comment by rai-nhdaly** [comment]
Although actually it's been a while since the last Release. Maybe we could tag a new one? :) Thanks!

**Comment by davidanthoff** [comment]
We just (an hour ago or so) release a new version of the VS Code extension that should include the ``master`` release of this repo. I even have a tag for this repo, just waiting for Zac to give me push access so that I can tag a release here as well!

**Comment by rai-nhdaly** [comment]
Thanks! :)
