### ISSUE TITLE
CSTParser.LeafNode missing

### ISSUE THREAD

**Issue by simonschnake** [ZacLN/DocumentFormat.jl#35]
ERROR: LoadError: UndefVarError: LeafNode not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] top-level scope at none:2
in expression starting at ..../src/DocumentFormat.jl:41

I have looked into CSTParser and CSTParser.LeafNode seems to be missing.

**Comment by ZacLN** [comment]
I'm just tagging a new release (compatible with the newer CSTParser version) in the mean time, and until I retroactively sort out the compat restrictions, dev'ing this will fix that issue

**Comment by davidanthoff** [comment]
I'll close this then.
